global:
    scrape_interval: 2s

scrape_configs:
    -   job_name: 'prometheus'
        static_configs:
            -   targets: [ 'host.docker.internal:9090' ]
    -   job_name: 'api-gateway'
        scrape_interval: 2s
        metrics_path: '/actuator/prometheus'
        static_configs:
            -   targets: [ 'host.docker.internal:10400' ]
    -   job_name: 'domain-service'
        scrape_interval: 2s
        metrics_path: '/actuator/prometheus'
        static_configs:
            -   targets: [ 'host.docker.internal:8081' ]
    -   job_name: 'auth-service'
        scrape_interval: 2s
        metrics_path: '/actuator/prometheus'
        static_configs:
            -   targets: [ 'host.docker.internal:8081' ]
